### PR TITLE
Added support for multipart uploads

### PR DESCRIPTION
**Pull request by satie**
Added support for multipart uploads using [multer](https://github.com/expressjs/multer).

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @satie, why is a multi-part upload needed for a function? Ideally we should be running read-only. Could this be passed in via the body instead?

If the file is too large then store it in S3/Minio before pulling into /tmp/ for use in the function.

Alex

**Comment by rimiti** [comment]
I'm totally agree with @alexellis, you should not use multipart.

**Comment by alexellis** [comment]
Derek close: inactive PR

**Comment by satie** [comment]
@alexellis - my apologies for not following up. I agree with the recommendation to not use multipart. For my use case, I am now uploading files to [minio](https://github.com/minio/minio) and passing the object information to the function.

Thank you for your support!

**Comment by alexellis** [comment]
No problems. What are you using it for now?

**Pull request closed without merging**
